### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/awesome-doctrine#5]
I'm [not motivated](https://github.com/sindresorhus/awesome/issues/927#issuecomment-290901412) to maintain this list and I don't want to let it die.

@hkulekci Hey, since you've contributes this list, would you be interested in taking it over? 

Thanks @lukasz-madon [for the idea](https://github.com/sindresorhus/awesome/issues/927#issuecomment-291004258)

**Comment by TomasVotruba** [comment]
Deprecating list at the moment. Let me know if anyone reading this is interested.

**Comment by hkulekci** [comment]
Hello @TomasVotruba sorry, I am late a bit. I want to take it over, I dont know I can handle all the requests because I am not really good at English. As you understand, I am trying to improve. On the other hand, I am using Doctrine in my projects and reading lots of documents on the internet. I believe that I can improve this list. But, you are right at some point. Doctrine development is moving slowly but I think, it is natural. Maybe, we can move the list [our community](https://github.com/biberlabs) organization if you want? There is some of my friends who are using doctrine and zend ecosystems in their projects.

**Comment by TomasVotruba** [comment]
Hi @hkulekci , thanks for the reply!

Sure I can move the repo. I'd be happy to be continued under somebody who would love to develop it more and more.

**Comment by TomasVotruba** [comment]
It looks like I need a permission there. Could you give me one please?

![image](https://cloud.githubusercontent.com/assets/924196/24772809/08db2904-1b13-11e7-9e1a-16cfd8c480d0.png)

**Comment by hkulekci** [comment]
@TomasVotruba I invited you as member.

**Comment by TomasVotruba** [comment]
Aaaaaand done, thank you :clap:

**Comment by hkulekci** [comment]
@TomasVotruba 👍  Could I remove deprecation messages?

**Comment by TomasVotruba** [comment]
@hkulekci Sure. You can do whatever you want. It's all yours now :)
